get:
  tags:
    - Products
  summary: List Products
  operationId: listProducts
  description: List all the Products
  parameters:
    - $ref: '../components/parameters/path/orgId.yml'
    - in: query
      name: name
      schema:
        type: string
      description: filter for the name of a product
    - in: query
      name: ownerOrganisationId
      schema:
        type: string
      description: filter for products of which organisations you want to see
    - in: query
      name: unitOfMeasurementIds
      schema:
        type: string
      description: filter for products with that unit of measurement
    - in: query
      name: allowedMaterialIds
      schema:
        type: array
        items:
          type: string
      description: filter for products with any of those allowed materials
  responses:
    '200':
      description: Array of Products
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '../components/schemas/productInfo.yml'
    '404':
      description: Invalid input
      content:
        application/json:
          schema:
            $ref: '../components/responses/404-notFound.yml'
    default:
      $ref: '../components/responses/400-unexpectedError.yml'
post:
  tags:
    - Products
  summary: Add Product
  operationId: addProduct
  description: Add a new Product
  parameters:
    - $ref: '../components/parameters/path/orgId.yml'
  requestBody:
    description: New Product information
    content:
      application/json:
        schema:
          $ref: '../components/schemas/newProduct.yml'
  responses:
    '201':
      description: Successful operation
      content:
        application/json:
          schema:
            $ref: '../components/schemas/product.yml'
    '422':
      description: Invalid input
      content:
        application/json:
          schema:
            $ref: '../components/responses/422-unprocessable.yml'
    default:
      $ref: '../components/responses/400-unexpectedError.yml'