put:
  tags:
    - Products
  x-badges:
    - color: blue
      label: Needs Review
  summary: Update product
  operationId: updateProduct
  description: This endpoint allows a product to be updated.
  parameters:
    - $ref: '../components/parameters/path/orgId.yml'
    - $ref: '../components/parameters/path/prodId.yml'
  requestBody:
    description: Update product information
    content:
      application/json:
        schema:
          $ref: '../components/schemas/product.yml'
    required: true
  responses:
    '201':
      description: Successful operation
      content:
        application/json:
          schema:
            $ref: '../components/schemas/product.yml'
    '400':
      $ref: '../components/responses/400-badRequest.yml'
    '401':
      $ref: '../components/responses/401-unauthorised.yml'
    '403':
      $ref: '../components/responses/403-forbidden.yml'
    '404':
      $ref: '../components/responses/404-notFound.yml'
    '429':
      $ref: '../components/responses/429-tooManyRequests.yml'
    default:
      $ref: '../components/responses/500-internalError.yml'
get:
  tags:
    - Products
  x-badges:
    - color: blue
      label: Needs Review
  summary: Get Product
  operationId: getProduct
  description: This endpoint returns the specific details for a given product.
  parameters:
    - $ref: '../components/parameters/path/orgId.yml'
    - $ref: '../components/parameters/path/prodId.yml'
  responses:
    '200':
      description: Product info
      content:
        application/json:
          schema:
            $ref: '../components/schemas/product.yml'
    '401':
      $ref: '../components/responses/401-unauthorised.yml'
    '403':
      $ref: '../components/responses/403-forbidden.yml'
    '404':
      $ref: '../components/responses/404-notFound.yml'
    '429':
      $ref: '../components/responses/429-tooManyRequests.yml'
    default:
      $ref: '../components/responses/500-internalError.yml'