get:
  tags:
    - Products
  x-badges:
    - color: blue
      label: Needs Review
  summary: List Products
  operationId: listProducts
  description: This endpoint returns all the products that have either been defined by the organisation or have been provided by other organisations.
  parameters:
    - $ref: '../components/parameters/path/orgId.yml'
    - $ref: '../components/parameters/query/page.yml'
    - $ref: '../components/parameters/query/size.yml'
  responses:
    '200':
      description: Array of Products
      content:
        application/json:
          schema:
            allOf:
              - $ref: '../components/schemas/pagination.yml'
              - type: object
                properties:
                  results: 
                    type: array
                    items: 
                      $ref: '../components/schemas/product.yml'
    '401':
      $ref: '../components/responses/401-unauthorised.yml'
    '403':
      $ref: '../components/responses/403-forbidden.yml'
    '429':
      $ref: '../components/responses/429-tooManyRequests.yml'
    default:
      $ref: '../components/responses/500-internalError.yml'
post:
  tags:
    - Products
  x-badges:
    - color: blue
      label: Needs Review
  summary: Add Product
  operationId: addProduct
  description: Add a new Product
  parameters:
    - $ref: '../components/parameters/path/orgId.yml'
  requestBody:
    description: Product information
    content:
      application/json:
        schema:
          $ref: '../components/schemas/product.yml'
  responses:
    '201':
      description: Successful operation
      content:
        application/json:
          schema:
            $ref: '../components/schemas/product.yml'
    '400':
      $ref: '../components/responses/400-badRequest.yml'
    '401':
      $ref: '../components/responses/401-unauthorised.yml'
    '403':
      $ref: '../components/responses/403-forbidden.yml'
    '429':
      $ref: '../components/responses/429-tooManyRequests.yml'
    default:
      $ref: '../components/responses/500-internalError.yml'