get:
  tags:
    - Products
  summary: List Products
  operationId: listProducts
  description: List all the Products
  parameters:
    - $ref: '../components/parameters/path/orgId.yml'
  responses:
    '200':
      description: Array of Products
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '../components/schemas/product.yml'
    default:
      $ref: '../components/responses/400-unexpectedError.yml'
post:
  tags:
    - Products
  summary: Add Product
  operationId: addProduct
  description: Add a new Product
  parameters:
    - $ref: '../components/parameters/path/orgId.yml'
  requestBody:
    description: Product information
    content:
      application/json:
        schema:
          $ref: '../components/schemas/product.yml'
  responses:
    '201':
      description: Successful operation
      content:
        application/json:
          schema:
            $ref: '../components/schemas/product.yml'
    '422':
      description: Invalid input
      content:
        application/json:
          schema:
            $ref: '../components/responses/422-unprocessable.yml'
    default:
      $ref: '../components/responses/400-unexpectedError.yml'