openapi: 3.1.0
info:
  title: Traceability API
  description: >-
    This API spec defines how you can interact with the iov42 traceability
    system.
  version: 0.9.13
servers:
  - url: https://reqres.in/api
    description: Mock API Service.
security:
  - ApiKeyAuth: []
  - JWTBearer: []
tags:
  - name: Signup 
    x-tag-expanded: false
    description: Set of APIs used to deal with user registration and invitations to other users.
  - name: Session
    x-tag-expanded: false
    description: Set of APIs used for Session handling.
  - name: Common
    x-tag-expanded: false
    description: Set of APIs providing data that is common across all organisations.
  - name: Profile
    x-tag-expanded: false
    description: Set of APIs used for various user profile operations.
  - name: Organisation
    x-tag-expanded: false
    description: Set of APIs used to manage information about an organisation itself.
  - name: Config
    x-tag-expanded: false
    description: Set of APIs used for defining key configuration information used in other areas of the system.
  - name: Supply Setup
    x-tag-expanded: false
    description: Set of APIs used for defining an organisations supply chain.
  - name: Supply
    x-tag-expanded: false
    description: Set of APIs used for tracking supply of items through the supply chain.
  - name: Evidence
    x-tag-expanded: false
    description: Set of APIs used to manage the data that is captured as evidence to support the Supply Chain and Supply captured in the system.
  - name: Metadata
    x-tag-expanded: true
    #description: Set of APIs used to manage metadata that is attached to records to capture extra information.
  - name: Attachments
    x-tag-expanded: true
    #description: Set of APIs used to manage metadata that is attached to records to capture extra information.



paths:
  /auth/token:
    $ref: ./paths/accessRequest.yml
  /auth/token/refresh:
    $ref: ./paths/accessRefresh.yml
  /auth/forgot-password:
    $ref: ./paths/forgotPassword.yml
  /auth/reset-password:
    $ref: ./paths/resetPassword.yml
  /organisations:
    $ref: ./paths/organisations.yml
  /organisations/{orgId}:
    $ref: ./paths/organisation.yml
  /organisations/{orgId}/attachments:
    $ref: ./paths/attachments.yml
  /organisations/{orgId}/attachments/{attachId}:
    $ref: ./paths/attachment.yml
  /organisations/{orgId}/certificates:
    $ref: ./paths/certificates.yml
  /organisations/{orgId}/certificates/{certId}:
    $ref: ./paths/certificate.yml
  #/organisations/{orgId}/checks:
  #  $ref: ./paths/checks.yml
  #/organisations/{orgId}/checks/{checkId}:
  #  $ref: ./paths/check.yml
  /organisations/{orgId}/connections:
    $ref: ./paths/connections.yml
  /organisations/{orgId}/connections/{conId}:
    $ref: ./paths/connection.yml
  # /organisations/{orgId}/custom-fields:
  #   $ref: ./paths/customFields.yml
  # /organisations/{orgId}/custom-fields/{cfId}:
  #   $ref: ./paths/customField.yml
  #/organisations/{orgId}/custom-field-definitions:
  #  $ref: ./paths/customFieldDefinitions.yml
  #/organisations/{orgId}/custom-field-definitions/{cfdId}:
  #  $ref: ./paths/customFieldDefinition.yml
  /organisations/{orgId}/deliveries:
    $ref: ./paths/deliveries.yml
  /organisations/{orgId}/deliveries/{deliveryId}:
    $ref: ./paths/delivery.yml
  /organisations/{orgId}/documents:
    $ref: ./paths/documents.yml
  /organisations/{orgId}/documents/{docId}:
    $ref: ./paths/document.yml
  /organisations/{orgId}/documents/{docId}/content:
    $ref: ./paths/documentContent.yml
  /organisations/{orgId}/document-types:
    $ref: ./paths/documentTypes.yml
  /organisations/{orgId}/document-types/{docTypeId}:
    $ref: ./paths/documentType.yml
  /organisations/{orgId}/locations:
    $ref: ./paths/locations.yml
  /organisations/{orgId}/locations/{locId}:
    $ref: ./paths/location.yml
  /organisations/{orgId}/location-types:
    $ref: ./paths/locationTypes.yml
  /organisations/{orgId}/location-types/{locTypeId}:
    $ref: ./paths/locationType.yml
  /organisations/{orgId}/location-links:
    $ref: ./paths/locationLinks.yml
  /organisations/{orgId}/location-links/{linkId}:
    $ref: ./paths/locationLink.yml
  /organisations/{orgId}/items:
    $ref: ./paths/items.yml
  /organisations/{orgId}/items/{itemId}:
    $ref: ./paths/item.yml
  #/organisations/{orgId}/mappings:
  #  $ref: ./paths/mappings.yml
  #/organisations/{orgId}/mappings/{mapId}:
  #  $ref: ./paths/mapping.yml
  /organisations/{orgId}/materials:
    $ref: ./paths/materials.yml
  /organisations/{orgId}/materials/{matId}:
    $ref: ./paths/material.yml
  /organisations/{orgId}/material-categories:
    $ref: ./paths/materialCategories.yml
  /organisations/{orgId}/products:
    $ref: ./paths/products.yml
  /organisations/{orgId}/products/{prodId}:
    $ref: ./paths/product.yml
  #/organisations/{orgId}/public:
  #  $ref: ./paths/public.yml
  /organisations/{orgId}/tags:
    $ref: ./paths/tags.yml
  /organisations/{orgId}/tags/{tagId}:
    $ref: ./paths/tag.yml
  /organisations/{orgId}/units:
    $ref: ./paths/userDefinedUnits.yml
  /organisations/{orgId}/units/{unitId}:
    $ref: ./paths/userDefinedUnit.yml
  /users/{userId}:
    $ref: ./paths/Users/user.yml
  /users/{userId}/organisations:
    $ref: ./paths/Users/userOrganisations.yml
  /users/{userId}/organisations/{orgId}:
    $ref: ./paths/Users/userOrganisation.yml
  /users/{userId}/organisations/{orgId}/leave:
    $ref: ./paths/Users/leaveOrganisation.yml
  /users/{userId}/change-email:
    $ref: ./paths/Users/changeEmail.yml
  /users/{userId}/change-password:
    $ref: ./paths/Users/changePassword.yml
  /organisations/{orgId}/members:
    $ref: ./paths/OrgMembers/orgMembers.yml
  /organisations/{orgId}/members/{memberId}:
    $ref: ./paths/OrgMembers/orgMember.yml
  /organisations/{orgId}/members/{memberId}/status:
    $ref: ./paths/OrgMembers/orgMemberStatus.yml
  /organisations/{orgId}/members/{memberId}/role:
    $ref: ./paths/OrgMembers/orgMemberRole.yml
  /users/{userId}/api-tokens:
    $ref: ./paths/apiAccessTokens.yml
  /users/{userId}/api-tokens/{apiTokenId}:
    $ref: ./paths/apiAccessToken.yml
  /users/{userId}/api-tokens/{apiTokenId}/regenerate:
    $ref: ./paths/apiAccessTokenRegenerate.yml
  /registrations:
    $ref: ./paths/Registrations/registrations.yml
  /registrations/{registrationId}:
    $ref: ./paths/Registrations/registration.yml
  /registrations/{registrationId}/verify:
    $ref: ./paths/Registrations/registrationVerify.yml
  /registrations/{registrationId}/resend:
    $ref: ./paths/Registrations/registrationResend.yml
  /invitations:
    $ref: ./paths/Registrations/invitations.yml
  /invitations/{invitationId}:
    $ref: ./paths/Registrations/invitation.yml
  /invitations/{invitationId}/accept:
    $ref: ./paths/Registrations/invitationAccept.yml
  /invitations/{invitationId}/reject:
    $ref: ./paths/Registrations/invitationReject.yml
  /common/base-unit-types:
    $ref: ./paths/Common/baseUnitTypes.yml
  /common/base-units:
    $ref: ./paths/Common/baseUnits.yml
  /common/base-units/{unitId}:
    $ref: ./paths/Common/baseUnit.yml
  /common/standards:
    $ref: ./paths/Common/standards.yml
  /common/standards/{standardId}:
    $ref: ./paths/Common/standard.yml
  /common/standards/{standardId}/types:
    $ref: ./paths/Common/standardTypes.yml
  /common/standards/{standardId}/types/{standardTypeId}:
    $ref: ./paths/Common/standardType.yml
  /organisations/{orgId}/supply-chains:
    $ref: ./paths/supplyChains.yml
  /organisations/{orgId}/supply-chains/{scId}:
    $ref: ./paths/supplyChain.yml
  /common/countries:
    $ref: ./paths/Common/countries.yml
  #/organisations/{orgId}/templates:
  #  $ref: ./paths/templates.yml
  #/organisations/{orgId}/templates/{tmplId}:
  #  $ref: ./paths/template.yml
  /common/resource-types:
    $ref: ./paths/Common/resourceTypes.yml
components:
  schemas:
    $ref: ./components/schemas/_index.yml
  securitySchemes:
    ApiKeyAuth:
      $ref: ./components/securitySchemas/api_key.yml
    JWTBearer:
      $ref: ./components/securitySchemas/jwt_bearer.yml
