openapi: 3.1.0
info:
  title: Traceability API
  description: >-
    This API spec defines how you can interact with the iov42 traceability
    system.
  version: 0.0.9
security:
  - ApiKeyAuth: []
  - JWTBearer: []
tags:
  - name: Attachments
    description: Apis for the creation and retrieval of Attachments
  - name: Certificates
    description: Apis for the creation and retrieval of Certificates
  - name: Checks
    description: Apis for the creation and retrieval of Checks
  - name: Connections
    description: Apis for the creation and retrieval of Connections
  - name: CustomFields
    description: Apis for the creation and retrieval of CustomFields
  - name: Deliveries
    description: Apis for the creation and retrieval of Deliveries
  - name: Documents
    description: Apis for the creation and retrieval of Documents
  - name: Items
    description: Apis for the creation and retrieval of Items
  - name: Locations
    description: Apis for the creation and retrieval of Locations
  - name: Mappings
    description: Apis for the creation and retrieval of Mapping
  - name: Materials
    description: Apis for the creation and retrieval of Materials
  - name: Organisation
    description: Apis for the creation and retrieval of Organisation
  - name: Products
    description: Apis for the creation and retrieval of Products
  - name: Public
    description: >-
      Apis for organisational information that is 'public'. By public this
      information is available to any registered user.
  - name: Tags
    description: Apis for the creation and retrieval of tags.
  - name: Shared
    description: Apis with information shared across all organisations.
  - name: Users
    description: Apis for user related information.
paths:
  /organisations:
    $ref: ./paths/organisations.yml
  /organisations/{orgId}:
    $ref: ./paths/organisation.yml
  /organisations/{orgId}/attachments:
    $ref: ./paths/attachments.yml
  /organisations/{orgId}/attachments/{attachId}:
    $ref: ./paths/attachment.yml
  /organisations/{orgId}/certificates:
    $ref: ./paths/certificates.yml
  /organisations/{orgId}/certificates/{certId}:
    $ref: ./paths/certificate.yml
  /organisations/{orgId}/checks:
    $ref: ./paths/checks.yml
  /organisations/{orgId}/checks/{checkId}:
    $ref: ./paths/check.yml
  /organisations/{orgId}/connections:
    $ref: ./paths/connections.yml
  /organisations/{orgId}/connections/{conId}:
    $ref: ./paths/connection.yml
  /organisations/{orgId}/customFields:
    $ref: ./paths/customFields.yml
  /organisations/{orgId}/customFields/{cfId}:
    $ref: ./paths/customField.yml
  /organisations/{orgId}/customFieldDefinitions:
    $ref: ./paths/customFieldDefinitions.yml
  /organisations/{orgId}/customFieldDefinitions/{cfdId}:
    $ref: ./paths/customFieldDefinition.yml
  /organisations/{orgId}/customFieldTemplates:
    $ref: ./paths/customFieldTemplates.yml
  /organisations/{orgId}/customFieldTemplates/{cftId}:
    $ref: ./paths/customFieldTemplate.yml
  /organisations/{orgId}/deliveries:
    $ref: ./paths/deliveries.yml
  /organisations/{orgId}/deliveries/{deliveryId}:
    $ref: ./paths/delivery.yml
  /organisations/{orgId}/documents:
    $ref: ./paths/documents.yml
  /organisations/{orgId}/documents/{docId}:
    $ref: ./paths/document.yml
  /organisations/{orgId}/locations:
    $ref: ./paths/locations.yml
  /organisations/{orgId}/locations/{locId}:
    $ref: ./paths/location.yml
  /organisations/{orgId}/locations/{locId}/links:
    $ref: ./paths/locationLinks.yml
  /organisations/{orgId}/locations/{locId}/links/{linkId}:
    $ref: ./paths/locationLink.yml
  /organisations/{orgId}/items:
    $ref: ./paths/items.yml
  /organisations/{orgId}/items/{itemId}:
    $ref: ./paths/item.yml
  /organisations/{orgId}/mappings:
    $ref: ./paths/mappings.yml
  /organisations/{orgId}/mappings/{mapId}:
    $ref: ./paths/mapping.yml
  /organisations/{orgId}/materials:
    $ref: ./paths/materials.yml
  /organisations/{orgId}/materials/{matId}:
    $ref: ./paths/material.yml
  /organisations/{orgId}/products:
    $ref: ./paths/products.yml
  /organisations/{orgId}/products/{prodId}:
    $ref: ./paths/product.yml
  /organisations/{orgId}/public:
    $ref: ./paths/public.yml
  /organisations/{orgId}/tags:
    $ref: ./paths/tags.yml
  /organisations/{orgId}/tags/{tagId}:
    $ref: ./paths/tag.yml
  /organisations/{orgId}/users:
    $ref: ./paths/users.yml
  /organisations/{orgId}/users/{userId}:
    $ref: ./paths/user.yml
  /organisations/{orgId}/users/{userId}/apiTokens:
    $ref: ./paths/apiAccessTokens.yml
  /organisations/{orgId}/users/{userId}/apiTokens/{apiTokenId}:
    $ref: ./paths/apiAccessToken.yml
  /organisations/{orgId}/users/{userId}/apiTokens/{apiTokenId}/regenerate:
    $ref: ./paths/apiAccessTokenRegenerate.yml
  /units:
    $ref: ./paths/units.yml
  /units/{unitId}:
    $ref: ./paths/unit.yml
components:
  schemas:
    $ref: ./components/schemas/_index.yml
  securitySchemes:
    ApiKeyAuth:
      $ref: ./components/securitySchemas/api_key.yml
    JWTBearer:
      $ref: ./components/securitySchemas/jwt_bearer.yml
