type: object
description: This is a definition of a product
required:
  - name
  - allowedMaterials
  - baseUnit
properties:
  name:
    description: This is the name for the product.
    type: string
  allowedMaterials:
    description: URI(s) for the material(s) that are allowed to be used for this product.
    type: array
    items:
      type: string
  baseUnit:
    description: URI for the base unit of measurements that this product is based off.
    type: string
