type: object
description: This is a definition of a product
required:
  - name
  - allowedMaterials
  - baseUnit
properties:
  name:
    description: This is the name for the product.
    type: string
  allowedMaterials:
    description: URI for the materials that are allowed to be used for this product.
    type: array
    items:
      type: string
  baseUnit:
    description: URI for the base unit of measurements that this product is based off.
    type: string
  userDefinedUnits:
    description: List of URIs for user defined units that are attached to this Product for conversion purposes.
    type: array
    items:
      type: string

