type: object
description: This is a definition of a product
required:
  - name
properties:
  id:
    description: System provided identity field.
    type: string
  name:
    type: string
  materials:
    type: array
    items:
      $ref: './material.yml'
  unitOfMeasurement:
    $ref: './unit.yml'
